# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opBi8slsM-T9O-Bgd3XcZ4yYPrgrfeGQ
"""

import nltk
nltk.download('punkt')
from textblob import TextBlob
import pandas as pd
import re

# lancer le script ci-dessous au cas ou vous avez une erreur de type "UnicodeDecodeError" dû aux données extraites du fichier json.
"""
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
"""

Data_pos = pd.read_csv('yes_not_clean.csv') # idem pour le 'no_not_clean_from_json.csv'
Pos= Data_pos[['pmid','text']]

list_des_conclusions = []
d = Pos['text']
tab = d.to_numpy() # transformer dataFrame à un tableau

for i in tab:
  text = i
  blob = TextBlob(text)
  sous_sentenses = []
  for a in blob.sentences:
    sous_sentenses.append(str(a))
 
  a = int((len(sous_sentenses) * (3/4)))
  b = len(sous_sentenses)
  conclusion = sous_sentenses[a:b]
  conclusion = "".join(map(str, conclusion))

  list_des_conclusions.append(conclusion)

conclusion = pd.DataFrame(list_des_conclusions, columns=['conclusion'])
result = pd.concat([Pos, conclusion], axis=1, sort=False)

r1 = result[['pmid','conclusion']]
r1.to_csv('final_conclusion_of_yes_not_clean.csv')